services:
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: postgres:15
    env_file: .env
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy